### ISSUE TITLE
Не запускается jar в тестовом режиме 

### ISSUE THREAD

**Issue by ZSemen47** [ZSemen47/TestMode#1]
### Шаги воспроизведения

1. Создать репозиторий
2. Добавить в каталог artifacts файл [app-ibank.jar](https://github.com/netology-code/aqa-homeworks/blob/aqa4/patterns/app-ibank.jar)
3. Запустить jar из консоли idea командой

> java -jar app-ibank.jar -P:profile=test

### Ожидаемый результат

- Тестовый режим запускается

### Фактический результат

- В консоли появляется сообщение об ошибке 

> Error: Unable to access jarfile app-ibank.jar

### Скриншот ошибки
![image](https://user-images.githubusercontent.com/65822156/106367131-774d7d80-6351-11eb-8543-4bd7034ef09d.png)

### Окружение 
Windows 10 pro x64
Java 11.0.7

**Comment by andrew-pahomov** [comment]
Добрый день. Исполняемый файл сервиса лежит в папке artifacts, а текущая папка это корень проекта, поэтому команда для его запуска будет немного другой                                    
`java -jar ./artifacts/app-ibank.jar -P:profile=test`
